services:
  node:
    container_name: node
    build: ./back-end
    ports:
      - 5000:5000
    env_file:
      - back-end/.env

  react:
    container_name: react
    build: ./front-end
    volumes:
      - react-volume:/var/www/html

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - node
      - react

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  react-volume:
