services:
  node:
    container_name: node
    build: ./back-end
    ports:
      - 5000:5000
    env_file:
      - back-end/.env

  react:
    container_name: react
    build: ./front-end
    volumes:
      - react-volume:/var/www/html

  nginx_app:
    restart: always
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - node
      - react

volumes:
  react-volume:
